version: '3'

services:
    app:
# we will build from local dockerfile instead of image from repo
        build:
            args:
                user: dev_user
                uid: 1000
            context: ./docker
            dockerfile: php.Dockerfile
        image: ${APP_NAME}
        container_name: ${APP_NAME}-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - appnet


    nginx:
        image: nginx:latest
        container_name: ${APP_NAME}-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - appnet

    mysql:
        image: mysql:8.0.23
        container_name: ${APP_NAME}-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - appnet

networks:
    appnet:
        driver: bridge
